_site/_site/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from home import views
from django.contrib import admin

# I8n URLs
urlpatterns = i18n_patterns(
    url(r'^$',               'home.views.index'),
    url(r'^admin/',          include(admin.site.urls)),
    url(r'^accounts/',       include('django.contrib.auth.urls')),
    url(r'^home/',           include('home.urls', namespace='home')),
    url(r'^user/',           include('user.urls', namespace='user')),
    url(r'^livro/',          include('livro.urls', namespace='livro')),
    url(r'^camiseta/',       include('camiseta.urls', namespace='camiseta')),
    url(r'^dvd/',            include('dvd.urls', namespace='dvd')),
    url(r'^jogoeletronico/', include('jogo_eletronico.urls', namespace='jogo')),
    url(r'^comments/',       include('django_comments.urls')),
)

_site/camiseta/urls.py
from django.conf.urls import url
from . import views

app_name = 'camiseta'

urlpatterns = [
	# /camiseta/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /camiseta/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /camiseta/add
    url(r'^add/$', views.CamisetaCreate.as_view(), name='camiseta-add'),

    # /camiseta/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.CamisetaUpdate.as_view(), name='camiseta-update'),

    #/camiseta/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.CamisetaDelete.as_view(), name='camiseta-delete'),
    
    #/camiseta/search/
    url(r'^search/$', views.search, name='camiseta-search'),
]

_site/dvd/urls.py
from django.conf.urls import url
from . import views

app_name = 'dvd'

urlpatterns = [
	# /dvd/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /dvd/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /dvd/add
    url(r'^add/$', views.DVDCreate.as_view(), name='dvd-add'),

    # /dvd/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.DVDUpdate.as_view(), name='dvd-update'),

    #/dvd/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.DVDDelete.as_view(), name='dvd-delete'),
    
    #/dvd/search/
    url(r'^search/$', views.search, name='dvd-search'),
]

_site/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /home/
    url(r'^', views.homepage, name='index'),
    
]

_site/jogo_eletronico/urls.py
from django.conf.urls import url
from . import views

app_name = 'jogo'

urlpatterns = [
	# /jogo/
    url(r'^$', views.IndexView.as_view(), name='index'),

   # /jogo/<id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /jogo/add
    url(r'^add/$', views.JogoCreate.as_view(), name='jogo-add'),

    # /jogo/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.JogoUpdate.as_view(), name='jogo-update'),

    #/jogo/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.JogoDelete.as_view(), name='jogo-delete'),

    #/jogo/search/
    url(r'^search/$', views.search, name='jogo-search'),
]

_site/livro/urls.py
from django.conf.urls import url
from . import views

app_name = 'livro'

urlpatterns = [
    # /livro/
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    # /livro/<id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /livro/add
    url(r'^add/$', views.LivroCreate.as_view(), name='livro-add'),

    # /livro/edit/<id>/
    url(r'^edit/(?P<pk>[0-9]+)/$', views.LivroUpdate.as_view(), name='livro-update'),

    #/livro/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.LivroDelete.as_view(), name='livro-delete'),

    #/livro/search/
    url(r'^search/$', views.search, name='livro-search'),
]

_site/user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

]

_site/home/models.py
from django.db import models

_site/home/views.py
from django.shortcuts import render, render_to_response
from django.views import generic
from django.template import RequestContext

def homepage(request):
	return render(request, 'home/index.html', {})

def index(request):
    return render_to_response('home/index.html')

_site/home/templates/home/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="pt-br">
<head>
	<title>{% block title %} Homepage {% endblock %}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 

	<!-- Tab Icon -->
	<link rel="Tab icon" href="http://www.dema.ufscar.br/portal/images/DEMa_Imagens/Logo/logoufscar.gif" />
<titled>

<!-- Header -->
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			
			<!-- Home Link -->
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'home:index' %}"><b> Home </b></a>
			</div>

			<!-- Itens -->
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<!-- Livros -->
					<li class="">
						<a href="{% url 'livro:index' %}"> {% trans "Livros" %}</a>
					</li>

					<!-- Jogos Eletrônicos -->
					<li class="">
						<a href="{% url 'jogo:index' %}"> {% trans "Jogos" %}</a>
					</li>

					<!-- Camisetas -->
					<li class="">
						<a href="{% url 'camiseta:index' %}"> {% trans "Camisetas" %}</a>
					</li>

					<!-- DVDs -->
					<li class="">
						<a href="{% url 'dvd:index' %}"> DVDs </a>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<!-- Opções de add, apenas se usuario estiver logado -->
					{% if request.user.is_authenticated %}
						<!-- Livro -->
						<li class="">
							<a href="{% url 'livro:livro-add' %}"> {% trans "Adicionar Livro" %} </a>
						</li>

						<!-- Jogo -->
						<li class="">
							<a href="{% url 'jogo:jogo-add' %}"> {% trans "Adicionar Jogo" %} </a>
						</li>

						<!-- Camiseta -->
						<li class="">
							<a href="{% url 'camiseta:camiseta-add' %}"> {% trans "Adicionar Camiseta" %} </a>
						</li>

						<!-- DVD -->
						<li class="">
							<a href="{% url 'dvd:dvd-add' %}"> {% trans "Adicionar" %} DVD </a>
						</li>
					{% endif %}

					<!-- Se usuario nao estiver logado, aparecer a opcao de login -->
					{% if not request.user.is_authenticated %}
						<!-- Cadastrar usuario -->
						<li>
							<a href="{% url 'user:register' %}"> {% trans "Cadastre" %} </a>
						</li>

						<!-- Logar usuario -->
						<li>
							<a href="{% url 'login' %}"> Login </a>
						</li>
					{% endif %}

					<!-- Se usuario estiver logado, aparecer a opcao de logout -->
					{% if request.user.is_authenticated %}
						<li>
							<a href="{% url 'logout' %}"> {% trans "Bem-Vindo" %}: {{user.username}}<br> Logout </a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
{% block body %}
{% endblock %}
</body>
</html>

_site/home/templates/home/form-template.html
{% load i18n %}

{% for field in form %}
	<div class="form-group">
		<label class="control-label col-sm-1"> {{field.label_tag}} </label>
		<div class="col-sm-10"> {{field}} </div>
	</div>
{% endfor %}

_site/home/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}
	<h1> Homepage do Catálogo </h1>
	<body>
		<h2> Texto teste </h2>
		<p> 
			Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
		</p>
		<p>
			Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
		</p>

		<!-- http://www.dema.ufscar.br/portal/images/DEMa_Imagens/Logo/logoufscar.gif -->
		<img style="margin:0px auto;display:block" src="http://www.dema.ufscar.br/portal/images/DEMa_Imagens/Logo/logoufscar.gif" height="300" width="420"/>
	</body>
{% endblock %}