_site/_site/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from home import views
from django.contrib import admin

# I8n URLs
urlpatterns = i18n_patterns(
    url(r'^$',               'home.views.index'),
    url(r'^admin/',          include(admin.site.urls)),
    url(r'^accounts/',       include('django.contrib.auth.urls')),
    url(r'^home/',           include('home.urls', namespace='home')),
    url(r'^user/',           include('user.urls', namespace='user')),
    url(r'^livro/',          include('livro.urls', namespace='livro')),
    url(r'^camiseta/',       include('camiseta.urls', namespace='camiseta')),
    url(r'^dvd/',            include('dvd.urls', namespace='dvd')),
    url(r'^jogoeletronico/', include('jogo_eletronico.urls', namespace='jogo')),
    url(r'^comments/',       include('django_comments.urls')),
)

_site/camiseta/urls.py
from django.conf.urls import url
from . import views

app_name = 'camiseta'

urlpatterns = [
	# /camiseta/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /camiseta/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /camiseta/add
    url(r'^add/$', views.CamisetaCreate.as_view(), name='camiseta-add'),

    # /camiseta/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.CamisetaUpdate.as_view(), name='camiseta-update'),

    #/camiseta/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.CamisetaDelete.as_view(), name='camiseta-delete'),
    
    #/camiseta/search/
    url(r'^search/$', views.search, name='camiseta-search'),
]

_site/dvd/urls.py
from django.conf.urls import url
from . import views

app_name = 'dvd'

urlpatterns = [
	# /dvd/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /dvd/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /dvd/add
    url(r'^add/$', views.DVDCreate.as_view(), name='dvd-add'),

    # /dvd/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.DVDUpdate.as_view(), name='dvd-update'),

    #/dvd/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.DVDDelete.as_view(), name='dvd-delete'),
    
    #/dvd/search/
    url(r'^search/$', views.search, name='dvd-search'),
]

_site/camiseta/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings

class Camiseta(models.Model):
    marca   = models.CharField(verbose_name=_('Marca'),   max_length=20)
    tamanho = models.CharField(verbose_name=_('Tamanho'), max_length=10)
    cor     = models.CharField(verbose_name=_('Cor'), 	  max_length=10)
    tecido  = models.CharField(verbose_name=_('Tecido'),  max_length=30)   
    preco   = models.FloatField(verbose_name=_(u'Preço'))
    user    = models.ForeignKey(settings.AUTH_USER_MODEL)

    def get_absolute_url(self):
        return reverse('camiseta:detail', kwargs={'pk': self.pk}) 

    def __str__(self):
        return self.marca + ', ' + self.tamanho + ', ' + self.cor + ', ' + self.tecido

_site/camiseta/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy
from .models import Camiseta
from .filters import CamisetaFilter

def search(request):
    camiseta_list = Camiseta.objects.all()
    camiseta_filter = CamisetaFilter(request.GET, queryset=camiseta_list)
    return render(request, 'camiseta/camiseta_list.html', {'filter': camiseta_filter})

class IndexView(generic.ListView):
	template_name = 'camiseta/index.html'
	context_object_name = 'all_camiseta'

	def get_queryset(self):
		return Camiseta.objects.all()

class DetailView(generic.DetailView):
	model = Camiseta
	template_name = 'camiseta/detail.html'

# Camiseta's CRUD
# Create
class CamisetaCreate(CreateView):
	model = Camiseta
	fields = ['marca', 'tamanho', 'cor', 'tecido', 'preco']

	def form_valid(self, form):
		Camiseta = form.save(commit=False)
		Camiseta.user = self.request.user
		return super(CamisetaCreate, self).form_valid(form)

# Update
class CamisetaUpdate(UpdateView):
	model = Camiseta
	fields = ['marca', 'tamanho', 'cor', 'tecido', 'preco']

# Delete
class CamisetaDelete(DeleteView):
	model = Camiseta
	success_url = reverse_lazy('camiseta:index')

_site/camiseta/templates/camiseta/camiseta_form.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} {% trans "Adicionar Camiseta" %} {% endblock %}

{% block body %}
	<h3><b> {% trans "Digite os dados da camiseta" %} </b></h3>
	<form class="form-horizontal" action="" method="POST" >
		{% csrf_token %}
		{% include 'home/form-template.html' %}
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-primary active"> {% trans "Submeter" %} </button>
			</div>
		</div>
	</form> 
{% endblock %}

_site/camiseta/templates/camiseta/camiseta_list.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block body %}
	<form method="get">
    	{{ filter.form.as_p }}
    	<button type="submit"> {% trans "Procurar" %} </button>
  	</form> 
  	<br>

	{% block content %}
		<ul>		
			{% for camiseta in filter.qs %}
		    	<li> 
		    		<a href="{% url 'camiseta:detail' camiseta.id %}"> {{ camiseta.marca }} </a> 
		    		{% trans "por R$" %}{{ camiseta.preco }} 
		    	</li>

		  	{% endfor %}
	  	</ul>
	{% endblock %}
{% endblock %}

_site/camiseta/templates/camiseta/detail.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load comments %}
{% block title %} {% trans "Detalhes" %} {% endblock %}

{% block body %}
	<h2> {% trans "Camiseta" %}: {{camiseta.id}}</h2>
	<ul>
		<li> {% trans "Marca" %}:   {{camiseta.marca}}  </li>
		<li> {% trans "Tamanho" %}: {{camiseta.tamanho}}</li>
		<li> {% trans "Cor" %}: 	{{camiseta.cor}}    </li>
		<li> {% trans "Tecido" %}:  {{camiseta.tecido}} </li>
		<li> {% trans "Preço" %}: R${{camiseta.preco}}  </li>
	</ul>

	{% render_comment_list for camiseta %}

	{% if user.is_authenticated %}
	    {% get_comment_form for object as form %}
	    <form action="{% comment_form_target %}" method="POST">
	    {% csrf_token %}
	    {{ form.comment }}
	    <!--{{ form.honeypot }} -->
	    {{ form.content_type }}
	    {{ form.object_pk }}
	    {{ form.timestamp }}
	    {{ form.security_hash }}
	    <input type="hidden" name="next" value="{% url 'camiseta:detail' camiseta.id %}" />
	    <button type="submit" class="btn btn-primary active"> {% trans "Adicionar comentário" %} </button>
	    </form>
	{% else %}
    	<p> {% trans "Por favor" %} <a href="{% url 'login' %}"> log in </a> {% trans "para deixar um comentário." %} </p>
	{% endif %}

{% endblock %}

_site/camiseta/templates/camiseta/index.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} {% trans "Camisetas" %} {% endblock %}

{% block body %}
	{% if all_camiseta %}
	<h2> {% trans "Lista de camisetas" %} </h2>
		<a href="{% url 'camiseta:camiseta-search' %}" class="btn btn-primary active"> {% trans "Procurar Camisetas" %} </a>
		<u1>
		    {% for camiseta in all_camiseta %}
		    <!-- Detail -->
		    <li><a href="{% url 'camiseta:detail' camiseta.id %}">{{ camiseta.marca }}</a>
		 
				{% if request.user == camiseta.user or request.user.is_superuser %}
					<!-- Delete -->
					<form action="{% url 'camiseta:camiseta-delete' camiseta.id %}" method="POST" style="display: inline;">
					{% csrf_token %}
						<input type="hidden" name="camiseta_id" value="{{ camiseta.id }}"/>
						<button type="submit" class="btn btn-default btn-sm"> 
							<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
						</button>
					</form>
				{% endif %}

				{% if request.user == camiseta.user %}
					<!-- Edit -->
					<form action="{% url 'camiseta:camiseta-update' camiseta.id %}" method="POST" style="display: inline;">
					{% csrf_token %}
						<input type="hidden" name="camiseta_id" value="{{ camiseta.id }}"/>
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						</button>
					</form>
			{% endif %}
			</li>
			{% endfor %}
		</u1>
	{% else %}
		<h2> {% trans "Não há camisetas" %} </h2>
	{% endif %}
{% endblock %}