_site/_site/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from home import views
from django.contrib import admin

# I8n URLs
urlpatterns = i18n_patterns(
    url(r'^$',               'home.views.index'),
    url(r'^admin/',          include(admin.site.urls)),
    url(r'^accounts/',       include('django.contrib.auth.urls')),
    url(r'^home/',           include('home.urls', namespace='home')),
    url(r'^user/',           include('user.urls', namespace='user')),
    url(r'^livro/',          include('livro.urls', namespace='livro')),
    url(r'^camiseta/',       include('camiseta.urls', namespace='camiseta')),
    url(r'^dvd/',            include('dvd.urls', namespace='dvd')),
    url(r'^jogoeletronico/', include('jogo_eletronico.urls', namespace='jogo')),
    url(r'^comments/',       include('django_comments.urls')),
)

_site/dvd/urls.py
from django.conf.urls import url
from . import views

app_name = 'dvd'

urlpatterns = [
	# /dvd/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /dvd/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /dvd/add
    url(r'^add/$', views.DVDCreate.as_view(), name='dvd-add'),

    # /dvd/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.DVDUpdate.as_view(), name='dvd-update'),

    #/dvd/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.DVDDelete.as_view(), name='dvd-delete'),
    
    #/dvd/search/
    url(r'^search/$', views.search, name='dvd-search'),
]

_site/dvd/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings

class DVD(models.Model):
    titulo  = models.CharField(verbose_name=_(u'Título'), max_length=50)
    genero  = models.CharField(verbose_name=_(u'Gênero'), max_length=15)
    ano     = models.IntegerField(verbose_name=_('Ano'))
    duracao = models.IntegerField(verbose_name=_(u'Duração'))
    preco   = models.FloatField(verbose_name=_(u'Preço'))
    user    = models.ForeignKey(settings.AUTH_USER_MODEL)

    def get_absolute_url(self):
        return reverse('dvd:detail', kwargs={'pk': self.pk}) 

    def __str__(self):
        ano = str(self.ano)  
        duracao = str(self.duracao)
        return self.titulo + ', ' + self.genero + ', ' + ano + ', ' + duracao

_site/dvd/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy
from .models import DVD
from .filters import DVDFilter

def search(request):
    DVD_list = DVD.objects.all()
    DVD_filter = DVDFilter(request.GET, queryset=DVD_list)
    return render(request, 'dvd/dvd_list.html', {'filter': DVD_filter})

class IndexView(generic.ListView):
	template_name = 'dvd/index.html'
	context_object_name = 'all_dvd'

	def get_queryset(self):
		return DVD.objects.all()

class DetailView(generic.DetailView):
	model = DVD
	template_name = 'dvd/detail.html'

# DVD's CRUD
# Create
class DVDCreate(CreateView):
	model = DVD
	fields = ['titulo', 'genero', 'ano', 'duracao', 'preco']
	
	def form_valid(self, form):
		DVD = form.save(commit=False)
		DVD.user = self.request.user
		return super(DVDCreate, self).form_valid(form)
		
# Update
class DVDUpdate(UpdateView):
	model = DVD
	fields = ['titulo', 'genero', 'ano', 'duracao', 'preco']

# Delete
class DVDDelete(DeleteView):
	model = DVD
	success_url = reverse_lazy('dvd:index')

_site/dvd/templates/dvd/detail.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load comments %}
{% block title %} {% trans "Detalhes" %} {% endblock %}

{% block body %}
	<h2> {% trans "Título" %}: {{dvd.titulo}}</h2>
	<ul>
		<li> {% trans "Gênero" %}:  {{dvd.genero}} </li>
		<li> {% trans "Ano" %}: 	{{dvd.ano}}    </li>
		<li> {% trans "Duração" %}: {{dvd.duracao}}</li>
		<li> {% trans "Preço" %}: R${{dvd.preco}}  </li>
	</ul>

{% render_comment_list for dvd %}

	{% if user.is_authenticated %}
	    {% get_comment_form for object as form %}
	    <form action="{% comment_form_target %}" method="POST">
	    {% csrf_token %}
	    {{ form.comment }}
	    <!--{{ form.honeypot }} -->
	    {{ form.content_type }}
	    {{ form.object_pk }}
	    {{ form.timestamp }}
	    {{ form.security_hash }}
	    <input type="hidden" name="next" value="{% url 'dvd:detail' dvd.id %}" />
	    <button type="submit" class="btn btn-primary active"> {% trans "Adicionar comentário" %} </button>
	    </form>
	{% else %}
    	<p> {% trans "Por favor" %} <a href="{% url 'login' %}"> log in </a> {% trans "para deixar um comentário." %} </p>
	{% endif %}

{% endblock %}

_site/dvd/templates/dvd/dvd_form.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} {% trans "Adicionar DVD" %} {% endblock %}

{% block body %}
	<h3><b> {% trans "Digite os dados do DVD" %} </b></h3>
	<form class="form-horizontal" action="" method="POST" >
		{% csrf_token %}
		{% include 'home/form-template.html' %}
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-primary active""> {% trans "Submeter" %} </button>
			</div>
		</div>
	</form> 
{% endblock %}

_site/dvd/templates/dvd/dvd_list.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block body %}
	<form method="get">
    	{{ filter.form.as_p }}
    	<button type="submit" class="btn btn-primary active"> {% trans "Procurar" %} </button>
  	</form> 
  	<br>

	{% block content %}
		<ul>		
			{% for dvd in filter.qs %}
		    	<li> 
		    		<a href="{% url 'dvd:detail' dvd.id %}"> {{ dvd.titulo }} </a> ({% trans "Ano" %}: {{ dvd.ano }})
		    	</li>
		  	{% endfor %}
	  	</ul>
	{% endblock %}
{% endblock %}

_site/dvd/templates/dvd/index.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} DVDs {% endblock %}

{% block body %}
	{% if all_dvd %}
	<h2> {% trans "Lista de DVDs" %} </h2>
		<a href="{% url 'dvd:dvd-search' %}" class="btn btn-primary active"> {% trans "Procurar DVDs" %} </a>
		<u1>
		    {% for dvd in all_dvd %}
		    <li><a href="{% url 'dvd:detail' dvd.id %}">{{ dvd.titulo }}</a>		 
			 	{% if request.user == dvd.user or request.user.is_superuser %}
				 	<!-- Delete -->
					<form action="{% url 'dvd:dvd-delete' dvd.id %}" method="POST" style="display: inline;">
						{% csrf_token %}
						<input type="hidden" name="dvd_id" value="{{ dvd.id }}"/>
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
						</button>
					</form>
				{% endif %}

				{% if request.user == dvd.user %}
					<!-- Edit -->
					<form action="{% url 'dvd:dvd-update' dvd.id %}" method="POST" style="display: inline;">
					{% csrf_token %}
						<input type="hidden" name="dvd_id" value="{{ dvd.id }}"/>
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						</button>
					</form>
				{% endif %}	
			</li>
			{% endfor %}
		</u1>
	{% else %}
		<h2> {% trans "Não há DVDs" %} </h2>
	{% endif %}
{% endblock %}