_site/_site/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from home import views
from django.contrib import admin

# I8n URLs
urlpatterns = i18n_patterns(
    url(r'^$',               'home.views.index'),
    url(r'^admin/',          include(admin.site.urls)),
    url(r'^accounts/',       include('django.contrib.auth.urls')),
    url(r'^home/',           include('home.urls', namespace='home')),
    url(r'^user/',           include('user.urls', namespace='user')),
    url(r'^livro/',          include('livro.urls', namespace='livro')),
    url(r'^camiseta/',       include('camiseta.urls', namespace='camiseta')),
    url(r'^dvd/',            include('dvd.urls', namespace='dvd')),
    url(r'^jogoeletronico/', include('jogo_eletronico.urls', namespace='jogo')),
    url(r'^comments/',       include('django_comments.urls')),
)

_site/dvd/urls.py
from django.conf.urls import url
from . import views

app_name = 'dvd'

urlpatterns = [
	# /dvd/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /dvd/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /dvd/add
    url(r'^add/$', views.DVDCreate.as_view(), name='dvd-add'),

    # /dvd/edit/<id>/
    url(r'^/edit/(?P<pk>[0-9]+)/$', views.DVDUpdate.as_view(), name='dvd-update'),

    #/dvd/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.DVDDelete.as_view(), name='dvd-delete'),
    
    #/dvd/search/
    url(r'^search/$', views.search, name='dvd-search'),
]

_site/livro/urls.py
from django.conf.urls import url
from . import views

app_name = 'livro'

urlpatterns = [
    # /livro/
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    # /livro/<id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /livro/add
    url(r'^add/$', views.LivroCreate.as_view(), name='livro-add'),

    # /livro/edit/<id>/
    url(r'^edit/(?P<pk>[0-9]+)/$', views.LivroUpdate.as_view(), name='livro-update'),

    #/livro/<id>/delete/
    url(r'(?P<pk>[0-9]+)/delete/$', views.LivroDelete.as_view(), name='livro-delete'),

    #/livro/search/
    url(r'^search/$', views.search, name='livro-search'),
]

_site/livro/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings

class Livro(models.Model):
    titulo  = models.CharField(verbose_name=_(u'Título'), max_length=100)
    ano     = models.IntegerField(verbose_name=_('Ano'))
    editora = models.CharField(verbose_name=_('Editora'), max_length=20)
    autora  = models.CharField(verbose_name=_('Autora'),  max_length=30)
    nroPags = models.IntegerField(verbose_name=_(u'Nro Páginas'))
    formato = models.CharField(verbose_name=_('Formato'), max_length=20)
    preco   = models.FloatField(verbose_name=_(u'Preço'))
    user    = models.ForeignKey(settings.AUTH_USER_MODEL)

    def get_absolute_url(self):
        return reverse('livro:detail', kwargs={'pk': self.pk}) 

    def __str__(self):
        ano = str(self.ano)  
        return self.titulo

_site/livro/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Livro
from .filters import LivroFilter

def search(request):
    Livro_list = Livro.objects.all()
    Livro_filter = LivroFilter(request.GET, queryset=Livro_list)
    return render(request, 'livro/livro_list.html', {'filter': Livro_filter})

class IndexView(generic.ListView):
	template_name = 'livro/index.html'
	context_object_name = 'all_livro'

	def get_queryset(self):
		return Livro.objects.all()


class DetailView(generic.DetailView):
	model = Livro
	template_name = 'livro/detail.html'

class LivroCreate(CreateView):
	model = Livro
	fields = ['titulo', 'ano', 'editora',
	'autora', 'nroPags', 'formato', 'preco']

	def form_valid(self, form):
		Livro = form.save(commit=False)
		Livro.user = self.request.user
		return super(LivroCreate, self).form_valid(form)


class LivroUpdate(UpdateView):
	model = Livro
	fields = ['titulo', 'ano', 'editora',
	'autora', 'nroPags', 'formato', 'preco']


class LivroDelete(DeleteView):
	model = Livro
	success_url = reverse_lazy('livro:index')

_site/livro/templates/livro/detail.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load comments %}
{% block title %} {% trans "Detalhes Livro" %} {% endblock %}

{% block body %}
	<h2> {% trans "Título" %}: {{livro.titulo}} </h2>
	<ul>
		<li> {% trans "Editora" %}: 	{{livro.editora}} </li>
		<li> {% trans "Ano" %}: 		{{livro.ano}} </li>
		<li> {% trans "Autora" %}:  	{{livro.autora}}</li>
		<li> {% trans "Nro Páginas" %}: {{livro.nroPags}} </li>
		<li> {% trans "Formato" %}: 	{{livro.formato}}</li>
		<li> {% trans "Preço" %}: R$	{{livro.preco}}</li>
	</ul>

	{% render_comment_list for livro %}

	{% if user.is_authenticated %}
	    {% get_comment_form for object as form %}
	    <form action="{% comment_form_target %}" method="POST">
	    {% csrf_token %}
	    {{ form.comment }}
	    <!--{{ form.honeypot }} -->
	    {{ form.content_type }}
	    {{ form.object_pk }}
	    {{ form.timestamp }}
	    {{ form.security_hash }}
	    <input type="hidden" name="next" value="{% url 'livro:detail' livro.id %}" />
	    <button type="submit" class="btn btn-primary active"> {% trans "Adicionar comentário" %} </button>
	    </form>
	{% else %}
    	<p> {% trans "Por favor" %} <a href="{% url 'login' %}"> log in </a> {% trans "para deixar um comentário." %} </p>
	{% endif %}

{% endblock %}

_site/livro/templates/livro/index.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} {% trans "Livros" %} {% endblock %}

{% block body %}
	{% if all_livro %}
	<h2> {% trans "Lista de livros" %} </h2>
	<a href="{% url 'livro:livro-search' %}" class="btn btn-primary active"> {% trans "Procurar Livros" %} </a>
	<u1>
	    {% for livro in all_livro %}
	    	<!-- Detail -->
		    <li><a href="{% url 'livro:detail' livro.id %}">{{ livro.titulo }}</a>
			 	
			 	{% if request.user == livro.user or request.user.is_superuser %}
				 	<!-- Delete -->
					<form action="{% url 'livro:livro-delete' livro.id %}" method="POST" style="display: inline;">
						{% csrf_token %}
						<input type="hidden" name="livro_id" value="{{ livro.id }}"/>
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
						</button>
					</form>
				{% endif %}

				{% if request.user == livro.user %}
					<!-- Edit -->
					<form action="{% url 'livro:livro-update' livro.id %}" method="POST" style="display: inline;">
					{% csrf_token %}
						<input type="hidden" name="livro_id" value="{{ livro.id }}"/>
						<button type="submit" class="btn btn-default btn-sm">
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						</button>
					</form>
				{% endif %}

			</li>
		{% endfor %}
	</u1>
	{% else %}
		<h2> {% trans "Não há Livros" %} </h2>
	{% endif %}
{% endblock %}

_site/livro/templates/livro/livro_form.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %} {% trans "Adicionar Livro" %} {% endblock %}

{% block body %}
	<h3><b> {% trans "Digite os dados do livro" %} </b></h3>
	<form class="form-horizontal" action="" method="POST">
		{% csrf_token %}
		{% include 'home/form-template.html' %}
		<div class="form-group">
			<div class="col-sm-offset-2">
				<button type="submit" class="btn btn-primary active"> {% trans "Submeter" %} </button>
			</div>
		</div>
	</form> 
{% endblock %}

_site/livro/templates/livro/livro_list.html
{% extends 'home/base.html' %}
{% load i18n %}

{% block body %}
	<form method="get">
    	{{ filter.form.as_p }}
    	<button type="submit" class="btn btn-primary active"> {% trans "Procurar" %} </button>
  	</form> 
  	<br>

	{% block content %}
		<ul>		
			{% for livro in filter.qs %}
		    	<li> 
		    		<a href="{% url 'livro:detail' livro.id %}"> {{ livro.titulo }} </a> ({% trans "Editora" %}: {{ livro.editora}})
		    	</li>
		  	{% endfor %}
	  	</ul>
	{% endblock %}
{% endblock %}